name = "Fabulously Optimized"
author = "robotkoer"
version = "4.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28364800f56d6c1bca90ace05156886d3aa70ddf8791919987a535f8dca4e21c"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
